const FUNERAL_HOMES = [

  {
    id: "FH0001",
    name: "Anatomy Bequest Program",
    city: "Mpls",
    address: "",
    photo: null,
    emails: ["AKALK2013@GMAIL.COM", "corneas@umn.edu"],
    phoneMain: "",
    phoneAlt: "",
    didNumber: "612-627-5657",
    hours: "Monday–Friday 8:00 am to 4:00 pm",
    contactOnAllCalls: true,
    firstCallInstructionsEmail: "corneas@umn.edu",
    answerScript: "Anatomy Bequest Program",
    flowerRoomHours: "",
    recommendedFlorists: [],
    specialInstructions: `First calls: Contact Lions Gift of Sight...`,
    directions: ``,
    notes: `### Special Instructions...`,
    website: "https://med.umn.edu/anatomy-bequest-program",
    obituaryLink: "",
    phone: "",
    backline: "",
    doorCode: "",
    groupId: "AB",
    locationFolderId: "",
    needsCoverage: true,
    chapelBranch: "AB",
    hasMultipleLocations: false,
    hasPetCremation: false
  },

  {
    id: "FH0002",
    name: "Anderson Funeral Home",
    city: "St. Paul",
    address: "1401 N Arcade St. St. Paul, 55106",
    photo: "images/Anderson-Banner.png",
    emails: [
      "AKALK2013@GMAIL.COM",
      "emily@andersonfuneralhome.com",
      "info@andersonfuneralhome.com"
    ],
    phoneMain: "",
    phoneAlt: "",
    didNumber: "612-627-6084",
    hours: "M-F 9-8pm, Sat-Sun 9-3pm",
    contactOnAllCalls: true,
    firstCallInstructionsEmail: "info@andersonfuneralhome.com",
    answerScript: "Anderson Funeral Home",
    flowerRoomHours: "M-F 9am–8pm, Sat–Sun 9am–3pm",
    recommendedFlorists: [
      { name: "Evans Floral", phone: "651-774-4544" },
      { name: "St Paul Floral", phone: "651-778-1661" }
    ],
    specialInstructions: `Text first, call cell if no response...`,
    directions: `From 35E: Exit Wheelock...`,
    notes: `### Special Instructions...`,
    website: "https://andersonfuneralhome.com/",
    obituaryLink: "https://andersonfuneralhome.com/tribute/all-services/index.html",
    phone: "651.776.2761",
    backline: "651.776.2762",
    doorCode: "",
    groupId: "AND",
    locationFolderId: "",
    needsCoverage: true,
    chapelBranch: "AND",
    hasMultipleLocations: false,
    hasPetCremation: false
  },

  {
    id: "FH0003",
    name: "Atkins Northland",
    city: "Cloquet",
    address: "801 14th St Cloquet MN 55720",
    photo: null,
    emails: [
      "AKALK2013@GMAIL.COM",
      "sophie.stone@atkinsnorthlandfuneralhome.com",
      "michael.dilley@csmcremation.com",
      "veronica.henschel@atkinsnorthlandfuneralhome.com"
    ],
    phoneMain: "218-879-7184",
    phoneAlt: "218-879-0133",
    didNumber: "612-627-5660",
    hours: "M-F 9-4pm",
    contactOnAllCalls: true,
    firstCallInstructionsEmail: "",
    answerScript: `“Atkins Northland Funeral Home...”`,
    flowerRoomHours: "",
    recommendedFlorists: [
      { name: "Skutevik’s Floral", phone: "218-879-6177" }
    ],
    specialInstructions: `Contact by text for urgent messages...`,
    directions: `Atkins-Northland: I‑35 → Hwy 33...`,
    notes: `### Special Instructions...`,
    website: "https://www.altogetherfuneral.com/funeral-cremation/minnesota/cloquet/atkins-northland-funeral-home/mnanf.html",
    obituaryLink: "https://www.altogetherfuneral.com/obituaries/?bids=dde3f72a-069d-11ef-b8a1-16dad070d26b",
    phone: "218.879.7184",
    backline: "",
    doorCode: "",
    groupId: "CMSD",
    locationFolderId: "",
    needsCoverage: true,
    chapelBranch: "CMSD",
    hasMultipleLocations: true,
    hasPetCremation: true
  },

  {
    id: "FH0004",
    name: "Ballard Sunder – Jordan",
    city: "Jordan",
    address: "104 1st St. W Jordan, MN",
    photo: "images/BS-logo-new-7da531b0-1920w.webp",
    emails: ["AKALK2013@GMAIL.COM", "office@ballardsunderfuneral.com"],
    phoneMain: "952.492.2818",
    phoneAlt: "612.789.3536",
    didNumber: "612-627-5620",
    hours: "",
    contactOnAllCalls: true,
    firstCallInstructionsEmail: "office@ballardsunderfuneral.com",
    answerScript: "Ballard Sunder Funeral and Cremation",
    flowerRoomHours: "",
    recommendedFlorists: [
      { name: "The Vinery", phone: "952-492-5222" },
      { name: "Stems and Vines", phone: "952-440-3200" },
      { name: "Pearson Florists", phone: "952-445-4344" },
      { name: "Shakopee Florist", phone: "952-445-4344" }
    ],
    specialInstructions: `Contact on all calls...`,
    directions: `Jordan Chapel: Hwy 169 → Hwy 21...`,
    notes: `### Special Instructions...`,
    website: "https://www.ballardsunderfuneral.com/",
    obituaryLink: "https://www.ballardsunderfuneral.com/obituaries",
    phone: "952.492.2818",
    backline: "612.789.3536",
    doorCode: "",
    groupId: "BSFH",
    locationFolderId: "",
    needsCoverage: true,
    chapelBranch: "BSFH",
    hasMultipleLocations: true,
    hasPetCremation: false
  },  {
    id: "FH0012",
    name: "Carlson-Lillemoen Funeral Home",
    city: "Cambridge",
    address: "311 Ashland Street S Cambridge, MN 55008",
    photo: null,
    emails: [
      "AKALK2013@GMAIL.COM",
      "jeff@carlsonlillemoen.com",
      "ty@carlsonlillemoen.com"
    ],
    phoneMain: "763.689.2244",
    phoneAlt: "",
    didNumber: "612-627-5668",
    hours: "M-F 8-5pm",
    contactOnAllCalls: true,
    firstCallInstructionsEmail: "jeff@carlsonlillemoen.com",
    answerScript: null,
    flowerRoomHours: "M-F 8-5pm (with exceptions for services)",
    recommendedFlorists: [
      { name: "Celebrate With Flowers", phone: "763-689-2040" }
    ],
    specialInstructions: `Directors prefer text. Flower door code: 1-5-4.`,
    directions: `North: Hwy 65 → County Rd 30 → 3rd Ave SW...`,
    notes: `### Special Instructions...`,
    website: "https://www.carlsonlillemoen.com",
    obituaryLink: "https://www.carlsonlillemoen.com/listings",
    phone: "763.689.2244",
    backline: "",
    doorCode: "154 floral, 9343 casket delivery",
    groupId: "CARL",
    locationFolderId: "",
    needsCoverage: true,
    chapelBranch: "CARL",
    hasMultipleLocations: false,
    hasPetCremation: false
  },

  {
    id: "FH0013",
    name: "Cremation Society of Minnesota – Minneapolis",
    city: "Minneapolis",
    address: "4343 Nicollet Ave S MPLS",
    photo: "images/Header-CMS-Logo.png",
    emails: ["AKALK2013@GMAIL.COM", "dispatch@csmcremation.com"],
    phoneMain: "612-825-2435",
    phoneAlt: "",
    didNumber: "612-627-6071",
    hours: "M-F 9-3:30pm, Sat/Sun by appointment",
    contactOnAllCalls: true,
    firstCallInstructionsEmail: "dispatch@csmcremation.com",
    answerScript: null,
    flowerRoomHours: "",
    recommendedFlorists: [],
    specialInstructions: `Scan and email first calls to dispatch@csmcremation.com.`,
    directions: `35W → 46th St → Nicollet Ave.`,
    notes: `### Special Instructions...`,
    website: "https://cremationsocietyofmn.com/",
    obituaryLink: "https://cremationsocietyofmn.com/tribute/all-services/index.html",
    phone: "612.825.2435",
    backline: "",
    doorCode: "",
    groupId: "CSM",
    locationFolderId: "",
    needsCoverage: false,
    chapelBranch: "CSM",
    hasMultipleLocations: true,
    hasPetCremation: true
  },

  {
    id: "FH0018",
    name: "Dare’s Funeral Home",
    city: "Elk River",
    address: "805 Main St Elk River 55330",
    photo: null,
    emails: [
      "AKALK2013@GMAIL.COM",
      "awichman@ohalloranmurphy.com",
      "cfonder@ohalloranmurphy.com",
      "cguerri@ohalloranmurphy.com",
      "eseterstrom@ohalloranmurphy.com",
      "jsteenson@ohalloranmurphy.com",
      "kkittock@ohalloranmurphy.com",
      "kleistico@ohalloranmurphy.com"
    ],
    phoneMain: "763.441.1212",
    phoneAlt: "763.441.4820",
    didNumber: "612-627-6082",
    hours: "M-F 8:30-4:30pm, Sat 8-12, Sun 9-12",
    contactOnAllCalls: true,
    firstCallInstructionsEmail: "",
    answerScript: null,
    flowerRoomHours: "M-F 8:30-4:30, Sat 8-12, Sun 9-12",
    recommendedFlorists: [
      { name: "Elk River Floral", phone: "763-441-3950" },
      { name: "101 Market", phone: "763-441-4487" },
      { name: "Flowers Plus", phone: "763-441-2598" }
    ],
    specialInstructions: `Owned by O’Halloran family. Alarm code: “hearse”.`,
    directions: `2 blocks west of Hwy 10 on Main St.`,
    notes: `### Special Instructions...`,
    website: "https://www.daresfuneralservice.com/listings",
    obituaryLink: "https://www.daresfuneralservice.com/listings",
    phone: "763.441.1212",
    backline: "763.441.4820",
    doorCode: "Alarm code hearse",
    groupId: "DPG",
    locationFolderId: "",
    needsCoverage: true,
    chapelBranch: "DPG",
    hasMultipleLocations: true,
    hasPetCremation: false
  },

  {
    id: "FH0019",
    name: "David Lee Funeral Home",
    city: "Wayzata",
    address: "1220 East Wayzata Blvd Wayzata MN 55391",
    photo: "images/DavidLee.png",
    emails: [
      "AKALK2013@GMAIL.COM",
      "jason@davidleefuneralhome.com",
      "mark@davidleefuneralhome.com"
    ],
    phoneMain: "952.473.5577",
    phoneAlt: "952.767.0719",
    didNumber: "612-627-5653",
    hours: "M-F open until dusk, Sat 9-11am",
    contactOnAllCalls: true,
    firstCallInstructionsEmail: "jason@davidleefuneralhome.com",
    answerScript: "David Lee Funeral Home",
    flowerRoomHours: "M-F until dusk, Sat 9-11am, Sun closed",
    recommendedFlorists: [
      { name: "Bonnie Keller", phone: "763-473-6462" }
    ],
    specialInstructions: `Contact on all calls.`,
    directions: `394 → 101 S/Wayzata Blvd → right.`,
    notes: `### Special Instructions...`,
    website: "https://www.davidleefuneralhome.com/",
    obituaryLink: "https://www.davidleefuneralhome.com/obituaries/obituary-listings?page=1",
    phone: "952.473.5577",
    backline: "952.767.0719",
    doorCode: "",
    groupId: "DLEE",
    locationFolderId: "",
    needsCoverage: true,
    chapelBranch: "DLEE",
    hasMultipleLocations: false,
    hasPetCremation: false
  },

  {
    id: "FH0020",
    name: "Evans Nordby Funeral Home – Brooklyn Center",
    city: "Brooklyn Center",
    address: "6000 Brooklyn Blvd Brooklyn Center",
    photo: "images/EvansNordby.png",
    emails: [
      "AKALK2013@GMAIL.COM",
      "brittney@evansnordby.com",
      "chelsea@evansnordby.com",
      "mike@evansnordby.com",
      "rachel@evansnordby.com",
      "tina@evansnordby.com"
    ],
    phoneMain: "763.533.3000",
    phoneAlt: "763.441.4820",
    didNumber: "612-627-5624",
    hours: "",
    contactOnAllCalls: true,
    firstCallInstructionsEmail: "",
    answerScript: "Evans Nordby Funeral Home",
    flowerRoomHours: "",
    recommendedFlorists: [
      { name: "Fairs Floral", phone: "763-424-6113" }
    ],
    specialInstructions: `Contact on all calls.`,
    directions: `1 mile south of 694.`,
    notes: `### Special Instructions...`,
    website: "https://www.evansnordby.com/",
    obituaryLink: "https://www.evansnordby.com/obituaries",
    phone: "763.533.3000",
    backline: "763.441.4820",
    doorCode: "",
    groupId: "EVNO",
    locationFolderId: "",
    needsCoverage: true,
    chapelBranch: "EVNO",
    hasMultipleLocations: true,
    hasPetCremation: false
  },

  {
    id: "FH0030",
    name: "Furever Loved Pet Cremation",
    city: "Cloquet",
    address: "",
    photo: null,
    emails: [
      "AKALK2013@GMAIL.COM",
      "marie.suonvieri@atkinsnorthlandfuneralhome.com"
    ],
    phoneMain: "",
    phoneAlt: "",
    didNumber: "",
    hours: "",
    contactOnAllCalls: false,
    firstCallInstructionsEmail: "",
    answerScript: null,
    flowerRoomHours: "",
    recommendedFlorists: [],
    specialInstructions: ``,
    directions: ``,
    notes: `Pet cremation service — limited information provided.`,
    website: "",
    obituaryLink: "",
    phone: "",
    backline: "",
    doorCode: "",
    groupId: "",
    locationFolderId: "",
    needsCoverage: false,
    chapelBranch: "",
    hasMultipleLocations: false,
    hasPetCremation: true
  },

  {
    id: "FH0028",
    name: "Gill Brothers – Bloomington",
    city: "Bloomington",
    address: "9947 Lyndale Ave S Mpls",
    photo: "images/GillBrothers.png",
    emails: ["AKALK2013@GMAIL.COM", "info@gillbrothers.com"],
    phoneMain: "952.888.7771",
    phoneAlt: "",
    didNumber: "612-627-5655",
    hours: "",
    contactOnAllCalls: true,
    firstCallInstructionsEmail: "info@gillbrothers.com",
    answerScript: "This is Gill Brothers",
    flowerRoomHours: "",
    recommendedFlorists: [
      { name: "HyVee Floral", phone: "763-531-7461" },
      { name: "Lake Harriet Florist", phone: "612-259-8211" },
      { name: "Richfield Florist", phone: "612-866-8416" },
      { name: "38th Street Florist", phone: "612-724-8484" }
    ],
    specialInstructions: `Send all pre-arrangement calls to Andrea.`,
    directions: ``,
    notes: `### Special Instructions...`,
    website: "https://www.gillbrothers.com/",
    obituaryLink: "https://www.gillbrothers.com/obituaries/obituary-listings?page=1",
    phone: "952.888.7771",
    backline: "",
    doorCode: "",
    groupId: "GILL",
    locationFolderId: "",
    needsCoverage: true,
    chapelBranch: "GILL",
    hasMultipleLocations: true,
    hasPetCremation: false
  },

  {
    id: "FH0029",
    name: "Gill Brothers – Minneapolis",
    city: "Minneapolis",
    address: "5801 Lyndale Ave S Mpls",
    photo: "images/GillBrothers.png",
    emails: ["AKALK2013@GMAIL.COM", "info@gillbrothers.com"],
    phoneMain: "612.861.6088",
    phoneAlt: "",
    didNumber: "612-627-5655",
    hours: "",
    contactOnAllCalls: true,
    firstCallInstructionsEmail: "info@gillbrothers.com",
    answerScript: "This is Gill Brothers",
    flowerRoomHours: "",
    recommendedFlorists: [
      { name: "HyVee Floral", phone: "763-531-7461" },
      { name: "Lake Harriet Florist", phone: "612-259-8211" },
      { name: "Richfield Florist", phone: "612-866-8416" },
      { name: "38th Street Florist", phone: "612-724-8484" }
    ],
    specialInstructions: `Same instructions as Bloomington.`,
    directions: ``,
    notes: `### Florists...`,
    website: "https://www.gillbrothers.com/",
    obituaryLink: "https://www.gillbrothers.com/obituaries/obituary-listings?page=1",
    phone: "612.861.6088",
    backline: "",
    doorCode: "",
    groupId: "GILL",
    locationFolderId: "",
    needsCoverage: true,
    chapelBranch: "GILL",
    hasMultipleLocations: true,
    hasPetCremation: false
  },
  {
    id: "FH0031",
    name: "Grandstrand Funeral Home – Lindstrom",
    city: "Lindstrom",
    address: "11900 Lake Ln N",
    photo: "images/Grandstrand.png",
    emails: [
      "AKALK2013@GMAIL.COM",
      "info@grandstrandfh.com"
    ],
    phoneMain: "651.257.4000",
    phoneAlt: "1234",
    didNumber: "612-627-5625",
    hours: "Weekdays 8:30-3:30, weekends vary",
    contactOnAllCalls: true,
    firstCallInstructionsEmail: "info@grandstrandfh.com",
    answerScript: null,
    flowerRoomHours: "Available anytime — florists use code 1234",
    recommendedFlorists: [
      { name: "Brinks’s Flowers", phone: "651-257-1700" },
      { name: "Floral Creations", phone: "651-257-1110" }
    ],
    specialInstructions: `Text directors first. Flower code: 1234.`,
    directions: `Hwy 8 → Shoquist → left → right at T → 1 mile down on left.`,
    notes: `### Special Instructions...`,
    website: "https://www.grandstrandfh.com/",
    obituaryLink: "https://www.grandstrandfh.com/obituaries/obituary-listings",
    phone: "651.257.4000",
    backline: "1234",
    doorCode: "1234",
    groupId: "GRAND",
    locationFolderId: "",
    needsCoverage: true,
    chapelBranch: "GRAND",
    hasMultipleLocations: true,
    hasPetCremation: false
  },

  {
    id: "FH0035",
    name: "Huber Funeral Home – Eden Prairie",
    city: "Eden Prairie",
    address: "Not provided (Eden Prairie Chapel address missing in source)",
    photo: "images/Huber.png",
    emails: [
      "AKALK2013@GMAIL.COM",
      "huberfh@hotmail.com",
      "paul@huberfunerals.com",
      "todd@huberfunerals.com"
    ],
    phoneMain: "",
    phoneAlt: "",
    didNumber: "612-627-5671",
    hours: "Weekdays 9AM–5PM, weekends vary",
    contactOnAllCalls: true,
    firstCallInstructionsEmail: "",
    answerScript: "Huber Funeral Home",
    flowerRoomHours: "Mound chapel front entrance always open for floral delivery",
    recommendedFlorists: [
      { name: "Pam Eggan Floral", phone: "763-442-9338" },
      { name: "Chanhassen Floral", phone: "952-949-2742" },
      { name: "Bayside Floral", phone: "952-471-8409" },
      { name: "Zinnia Design Florals", phone: "612-710-9150" }
    ],
    specialInstructions: `Prearrangement messages bypass on-call...`,
    directions: `### Eden Prairie Chapel...`,
    notes: `### Special Instructions...`,
    website: "https://www.huberfunerals.com/",
    obituaryLink: "",
    phone: "",
    backline: "",
    doorCode: "EP: 1892 ENTER; Excelsior: 1892 / 0+1892; Flower door: 23508",
    groupId: "HUB",
    locationFolderId: "",
    needsCoverage: true,
    chapelBranch: "HUB",
    hasMultipleLocations: true,
    hasPetCremation: false
  },

  {
    id: "FH0022",
    name: "JWFCS",
    city: "St. Paul",
    address: "",
    photo: null,
    emails: [
      "AKALK2013@GMAIL.COM",
      "answeringservice@jwfuneralcars.com"
    ],
    phoneMain: "763.533.3001",
    phoneAlt: "",
    didNumber: "",
    hours: "",
    contactOnAllCalls: true,
    firstCallInstructionsEmail: "",
    answerScript: null,
    flowerRoomHours: "",
    recommendedFlorists: [],
    specialInstructions: ``,
    directions: ``,
    notes: `No additional information provided.`,
    website: "",
    obituaryLink: "",
    phone: "763.533.3001",
    backline: "",
    doorCode: "",
    groupId: "JWFCS",
    locationFolderId: "",
    needsCoverage: true,
    chapelBranch: "JWFCS",
    hasMultipleLocations: false,
    hasPetCremation: false
  },

  {
    id: "FH0024",
    name: "Twin Cities Cremation",
    city: "St. Paul",
    address: "344 University Ave W, St Paul, MN 55103",
    photo: "images/Willwerscheid.png",
    emails: [
      "AKALK2013@GMAIL.COM",
      "info@willwersheid.com"
    ],
    phoneMain: "(651) 237-5056",
    phoneAlt: "",
    didNumber: "612-627-6075",
    hours: "M-F 9-5",
    contactOnAllCalls: true,
    firstCallInstructionsEmail: "info@willwerscheid.com",
    answerScript: "Funeral home — determine location",
    flowerRoomHours: "",
    recommendedFlorists: [
      { name: "A Johnson & Sons", phone: "651-698-6000" },
      { name: "Hermes Floral", phone: "651-646-7135" }
    ],
    specialInstructions: `Shared on-call director with Willwerscheid, Spielman, and EcremationMN.`,
    directions: `1 block east of Western Avenue.`,
    notes: `### Special Instructions...`,
    website: "https://www.altogetherfuneral.com/funeral-cremation/minnesota/st-paul/willwerscheid-funeral-home-cremation-grand-avenue/mnwga.html",
    obituaryLink: "https://www.altogetherfuneral.com/obituaries/?bids=de4915d8-069d-11ef-b8a1-16dad070d26b",
    phone: "(651) 237-5056",
    backline: "",
    doorCode: "",
    groupId: "WILL",
    locationFolderId: "",
    needsCoverage: true,
    chapelBranch: "WILL",
    hasMultipleLocations: true,
    hasPetCremation: false
  },

  {
    id: "FH0025",
    name: "EcremationMN",
    city: "St. Paul",
    address: "344 University Ave W St. Paul 55103",
    photo: "images/Willwerscheid.png",
    emails: [
      "AKALK2013@GMAIL.COM",
      "info@willwersheid.com"
    ],
    phoneMain: "651.237.4804",
    phoneAlt: "",
    didNumber: "612-627-6075",
    hours: "M-F 9-5",
    contactOnAllCalls: true,
    firstCallInstructionsEmail: "info@willwerscheid.com",
    answerScript: "Funeral home — determine location",
    flowerRoomHours: "",
    recommendedFlorists: [
      { name: "A Johnson & Sons", phone: "651-698-6000" },
      { name: "Hermes Floral", phone: "651-646-7135" }
    ],
    specialInstructions: `Shared on-call director with Willwerscheid, Spielman, and Twin Cities Cremation.`,
    directions: `1 block east of Western Avenue.`,
    notes: `### Special Instructions...`,
    website: "https://www.altogetherfuneral.com/funeral-cremation/minnesota/st-paul/willwerscheid-funeral-home-cremation-grand-avenue/mnwga.html",
    obituaryLink: "https://www.altogetherfuneral.com/obituaries/?bids=de4915d8-069d-11ef-b8a1-16dad070d26b",
    phone: "651.237.4804",
    backline: "",
    doorCode: "",
    groupId: "WILL",
    locationFolderId: "",
    needsCoverage: true,
    chapelBranch: "WILL",
    hasMultipleLocations: true,
    hasPetCremation: false
  },

  {
    id: "FH0026",
    name: "Willwerscheid West Heights Chapel",
    city: "Inver Grove Heights",
    address: "235 Wentworth Ave W West St. Paul 55118",
    photo: "images/Willwerscheid.png",
    emails: [
      "AKALK2013@GMAIL.COM",
      "info@willwersheid.com"
    ],
    phoneMain: "(651) 237-5056",
    phoneAlt: "",
    didNumber: "612-627-6075",
    hours: "M-F 9-5",
    contactOnAllCalls: true,
    firstCallInstructionsEmail: "info@willwerscheid.com",
    answerScript: "Funeral home — determine location",
    flowerRoomHours: "",
    recommendedFlorists: [
      { name: "A Johnson & Sons", phone: "651-698-6000" },
      { name: "Hermes Floral", phone: "651-646-7135" }
    ],
    specialInstructions: `Shared on-call director with Willwerscheid, Twin Cities Cremation, Spielman, and EcremationMN.`,
    directions: `1 mile west of Robert St on Wentworth.`,
    notes: `### Special Instructions...`,
    website: "https://www.altogetherfuneral.com/funeral-cremation/minnesota/st-paul/willwerscheid-funeral-home-cremation-grand-avenue/mnwga.html",
    obituaryLink: "https://www.altogetherfuneral.com/obituaries/?bids=de4915d8-069d-11ef-b8a1-16dad070d26b",
    phone: "(651) 237-5056",
    backline: "",
    doorCode: "",
    groupId: "WILL",
    locationFolderId: "",
    needsCoverage: true,
    chapelBranch: "WILL",
    hasMultipleLocations: true,
    hasPetCremation: false
  },

  {
    id: "FH0027",
    name: "Willwerscheid Grand Ave Chapel",
    city: "St. Paul",
    address: "1167 Grand Ave St. Paul MN 55105",
    photo: "images/Willwerscheid.png",
    emails: [
      "AKALK2013@GMAIL.COM",
      "info@willwersheid.com"
    ],
    phoneMain: "651.222.9918",
    phoneAlt: "",
    didNumber: "612-627-6075",
    hours: "M-F 9-5",
    contactOnAllCalls: true,
    firstCallInstructionsEmail: "info@willwerscheid.com",
    answerScript: "Funeral home — determine location",
    flowerRoomHours: "",
    recommendedFlorists: [
      { name: "A Johnson & Sons", phone: "651-698-6000" },
      { name: "Hermes Floral", phone: "651-646-7135" }
    ],
    specialInstructions: `Shared on-call director with Willwerscheid, Twin Cities Cremation, Spielman, and EcremationMN.`,
    directions: `1 block west of Lexington Parkway on Grand.`,
    notes: `### Special Instructions...`,
    website: "https://www.altogetherfuneral.com/funeral-cremation/minnesota/st-paul/willwerscheid-funeral-home-cremation-grand-avenue/mnwga.html",
    obituaryLink: "https://www.altogetherfuneral.com/obituaries/?bids=de4915d8-069d-11ef-b8a1-16dad070d26b",
    phone: "651.222.9918",
    backline: "",
    doorCode: "",
    groupId: "WILL",
    locationFolderId: "",
    needsCoverage: true,
    chapelBranch: "WILL",
    hasMultipleLocations: true,
    hasPetCremation: false
  }

]; 
